In [2]:
import numpy as np


# Creating a 1D NumPy array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
# Creating a 2D NumPy array
arr2 = np.array([[1, 2, 3], 
                 [4, 5, 6]])
print(arr2)
# Checking type and shape
print("Type:", type(arr1))
print("Shape:", arr2.shape)
print("Shape:", arr1.shape)
print("Dimension:",arr1.ndim)
print("Dimension:",arr2.ndim)
print("Data Type:",arr1.dtype)
print("Data Type:",arr2.dtype)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape: (2, 3)
Shape: (5,)
Dimension: 1
Dimension: 2
Data Type: int32
Data Type: int32


In [6]:
import numpy as np
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)
print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 4000 bytes


In [9]:
np.zeros((3, 3)) # 3x3 array of zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((2, 4)) # 2x4 array of ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.full((2, 2), 7) # 2x2 array filled with 7

array([[7, 7],
       [7, 7]])

In [13]:
np.eye(3) # 3 x 3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.arange(1, 55, 5) # [1, 3, 5, 7, 9] (like range)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51])

In [19]:
np.linspace(0,10,5) # [0. 0.25 0.5 0.75 1.] (evenly spaced)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape) # (2, 3)

(2, 3)


In [5]:
reshaped = arr.reshape((3, 2)) # Change shape
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
flattened = arr.flatten() # Convert 2D → 1D
print(flattened) # [1 2 3 4 5 6]

[1 2 3 4 5 6]
