In [1]:
# LETS START THE INDEXONG 

# DATE - 11TH FEB [IN CLG]

In [2]:
import numpy as np

arr=np.array([[1,2,3],
             [4,5,6],
             [7,8,9],
             [10,11,12]])

print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [3]:
print(arr.ndim)

2


In [5]:
arr1=arr.flatten()

print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [6]:
print(arr1[ : 12])

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [7]:
print(arr1[0 : ])

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [8]:
print(arr1[ 3:6 ])

[4 5 6]


In [9]:
print(arr1[ : : 2])

[ 1  3  5  7  9 11]


In [10]:
print(arr1[2 : 8 : 2])

[3 5 7]


In [11]:
# FANCY SLICING 

arr2=np.array([11,22,33,44,55,66,77,88,99])

print(arr2)


[11 22 33 44 55 66 77 88 99]


In [12]:
arrr=arr2.flatten()
print(arrr)

[11 22 33 44 55 66 77 88 99]


In [13]:
idx=[0,2,4,6,7]

print(arrr[idx])

[11 33 55 77 88]


In [14]:
#BOOLEAN MASKING


mask= arrr > 33
print(arrr[mask])

[44 55 66 77 88 99]
